[workspace]
authors = ["Howard Yen <howardy2000@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
channel-priority = "disabled"
name = "RetrievalTools"
platforms = ["linux-64"]
version = "0.1.0"


[system-requirements]
cuda = "12"

[dependencies]
python = "3.10.*"
pytorch-gpu = "*"
cuda-version = "12.6.*"
faiss-gpu = ">=1.13.0,<2"
fsspec = "<=2025.10.0"  # Pin to version compatible with datasets

[pypi-dependencies]
retrievaltools-py = { path = ".", editable = true }

[pypi-options]
no-build-isolation = ["flash-attn"]
