# this is the wikipedia 2019 corpus from KILT, split into 100 word passages
corpus_options:
  paths:
    - /scratch/gpfs/hyen/data/kilt/psgs_w100.tsv 
  text_field: text
  metadata_fields: [wikipedia_title]
  num_workers: 8

shard_options:
  shard_files: false